### DAV2008T

In [1]:
import os
import numpy as np
import pandas as pd
from pyprotolinc import _DEFAULT_TABLES_PATH

base_directory = os.path.join(_DEFAULT_TABLES_PATH, "Germany_Endowments_DAV2008T")
base_rates_path = os.path.abspath(os.path.join(base_directory, "Germany_Endowments_DAV2008T.csv"))
base_rates_path

'd:\\programming\\pymultistate\\pyprotolinc\\assumptions\\tables\\Germany_Endowments_DAV2008T\\Germany_Endowments_DAV2008T.csv'

In [2]:
tab_DAV2008T = pd.read_csv(base_rates_path, header=[0, 3, 4])
tab_DAV2008T.head()

DAV 2008T R/NR Männer Unnamed: 1_level_0         Unnamed: 2_level_0  \
                  Alter      Raucheranteil Raucher- übersterblichkeit   
     Unnamed: 0_level_2 Unnamed: 1_level_2         Unnamed: 2_level_2   
0                     0                 0%                       100%   
1                     1                 0%                       100%   
2                     2                 0%                       100%   
3                     3                 0%                       100%   
4                     4                 0%                       100%   

    Unnamed: 3_level_0       Unnamed: 4_level_0 Unnamed: 5_level_0  \
  Nichtraucher- faktor Sterblichkeit 2. Ordnung Unnamed: 5_level_1   
    Unnamed: 3_level_2                 Aggregat       Nichtraucher   
0                  1.0                 0.004562           0.004562   
1                  1.0                 0.000316           0.000316   
2                  1.0                 0.000256           0.000256   
3                  1.0                 0.000205           0.000205   
4                  1.0                 0.000164           0.000164   

  Unnamed: 6_level_0       Unnamed: 7_level_0          Unnamed: 8_level_0  \
  Unnamed: 6_level_1 Sterblichkeit 1. Ordnung          Unnamed: 8_level_1   
             Raucher  Aggregat (Zuschlag 34%) Nichtraucher (Zuschlag 45%)   
0           0.004562                 0.006113                    0.006113   
1           0.000316                 0.000423                    0.000423   
2           0.000256                 0.000343                    0.000343   
3           0.000205                 0.000275                    0.000275   
4           0.000164                 0.000220                    0.000220   

      Unnamed: 9_level_0 DAV 2008T R/NR Frauen Unnamed: 11_level_0  \
      Unnamed: 9_level_1                 Alter       Raucheranteil   
  Raucher (Zuschlag 45%)   Unnamed: 10_level_2 Unnamed: 11_level_2   
0               0.006615                     0                  0%   
1               0.000458                     1                  0%   
2               0.000371                     2                  0%   
3               0.000297                     3                  0%   
4               0.000238                     4                  0%   

         Unnamed: 12_level_0  Unnamed: 13_level_0      Unnamed: 14_level_0  \
  Raucher- übersterblichkeit Nichtraucher- faktor Sterblichkeit 2. Ordnung   
         Unnamed: 12_level_2  Unnamed: 13_level_2                 Aggregat   
0                       100%                  1.0                 0.003797   
1                       100%                  1.0                 0.000289   
2                       100%                  1.0                 0.000237   
3                       100%                  1.0                 0.000190   
4                       100%                  1.0                 0.000151   

  Unnamed: 15_level_0 Unnamed: 16_level_0      Unnamed: 17_level_0  \
  Unnamed: 15_level_1 Unnamed: 16_level_1 Sterblichkeit 1. Ordnung   
         Nichtraucher             Raucher  Aggregat (Zuschlag 34%)   
0            0.003797            0.003797                 0.005088   
1            0.000289            0.000289                 0.000387   
2            0.000237            0.000237                 0.000318   
3            0.000190            0.000190                 0.000255   
4            0.000151            0.000151                 0.000202   

          Unnamed: 18_level_0    Unnamed: 19_level_0  
          Unnamed: 18_level_1    Unnamed: 19_level_1  
  Nichtraucher (Zuschlag 45%) Raucher (Zuschlag 45%)  
0                    0.005088               0.005506  
1                    0.000387               0.000419  
2                    0.000318               0.000344  
3                    0.000255               0.000276  
4                    0.000202               0.000219

In [3]:
cols = tab_DAV2008T.columns
cols

MultiIndex([('DAV 2008T R/NR Männer',                      'Alter', ...),
            (   'Unnamed: 1_level_0',              'Raucheranteil', ...),
            (   'Unnamed: 2_level_0', 'Raucher- übersterblichkeit', ...),
            (   'Unnamed: 3_level_0',       'Nichtraucher- faktor', ...),
            (   'Unnamed: 4_level_0',   'Sterblichkeit 2. Ordnung', ...),
            (   'Unnamed: 5_level_0',         'Unnamed: 5_level_1', ...),
            (   'Unnamed: 6_level_0',         'Unnamed: 6_level_1', ...),
            (   'Unnamed: 7_level_0',   'Sterblichkeit 1. Ordnung', ...),
            (   'Unnamed: 8_level_0',         'Unnamed: 8_level_1', ...),
            (   'Unnamed: 9_level_0',         'Unnamed: 9_level_1', ...),
            ('DAV 2008T R/NR Frauen',                      'Alter', ...),
            (  'Unnamed: 11_level_0',              'Raucheranteil', ...),
            (  'Unnamed: 12_level_0', 'Raucher- übersterblichkeit', ...),
            (  'Unnamed: 13_level_0', 

In [4]:
# forward fill headers
filled_headers = [[], [], []]

for row_count, ind_row in enumerate(cols):
    for l in range(len(filled_headers)):
        if row_count > 0 and ind_row[l].startswith("Unnamed:"):
            filled_headers[l].append(filled_headers[l][-1])
        else:
            filled_headers[l].append(ind_row[l])
filled_headers

[['DAV 2008T R/NR Männer',
  'DAV 2008T R/NR Männer',
  'DAV 2008T R/NR Männer',
  'DAV 2008T R/NR Männer',
  'DAV 2008T R/NR Männer',
  'DAV 2008T R/NR Männer',
  'DAV 2008T R/NR Männer',
  'DAV 2008T R/NR Männer',
  'DAV 2008T R/NR Männer',
  'DAV 2008T R/NR Männer',
  'DAV 2008T R/NR Frauen',
  'DAV 2008T R/NR Frauen',
  'DAV 2008T R/NR Frauen',
  'DAV 2008T R/NR Frauen',
  'DAV 2008T R/NR Frauen',
  'DAV 2008T R/NR Frauen',
  'DAV 2008T R/NR Frauen',
  'DAV 2008T R/NR Frauen',
  'DAV 2008T R/NR Frauen',
  'DAV 2008T R/NR Frauen'],
 ['Alter',
  'Raucheranteil',
  'Raucher- übersterblichkeit',
  'Nichtraucher- faktor',
  'Sterblichkeit 2. Ordnung',
  'Sterblichkeit 2. Ordnung',
  'Sterblichkeit 2. Ordnung',
  'Sterblichkeit 1. Ordnung',
  'Sterblichkeit 1. Ordnung',
  'Sterblichkeit 1. Ordnung',
  'Alter',
  'Raucheranteil',
  'Raucher- übersterblichkeit',
  'Nichtraucher- faktor',
  'Sterblichkeit 2. Ordnung',
  'Sterblichkeit 2. Ordnung',
  'Sterblichkeit 2. Ordnung',
  'Sterblichk

In [5]:
new_headers = pd.MultiIndex.from_arrays(filled_headers, names=('GENDER_IND', 'PRUDENCE_RELATED', "SMOKER_RELATED"))
new_headers

MultiIndex([('DAV 2008T R/NR Männer',                      'Alter', ...),
            ('DAV 2008T R/NR Männer',              'Raucheranteil', ...),
            ('DAV 2008T R/NR Männer', 'Raucher- übersterblichkeit', ...),
            ('DAV 2008T R/NR Männer',       'Nichtraucher- faktor', ...),
            ('DAV 2008T R/NR Männer',   'Sterblichkeit 2. Ordnung', ...),
            ('DAV 2008T R/NR Männer',   'Sterblichkeit 2. Ordnung', ...),
            ('DAV 2008T R/NR Männer',   'Sterblichkeit 2. Ordnung', ...),
            ('DAV 2008T R/NR Männer',   'Sterblichkeit 1. Ordnung', ...),
            ('DAV 2008T R/NR Männer',   'Sterblichkeit 1. Ordnung', ...),
            ('DAV 2008T R/NR Männer',   'Sterblichkeit 1. Ordnung', ...),
            ('DAV 2008T R/NR Frauen',                      'Alter', ...),
            ('DAV 2008T R/NR Frauen',              'Raucheranteil', ...),
            ('DAV 2008T R/NR Frauen', 'Raucher- übersterblichkeit', ...),
            ('DAV 2008T R/NR Frauen', 

In [6]:
tab_DAV2008T.columns = new_headers
tab_DAV2008T.head()

GENDER_IND       DAV 2008T R/NR Männer                     \
PRUDENCE_RELATED                 Alter      Raucheranteil   
SMOKER_RELATED      Unnamed: 0_level_2 Unnamed: 0_level_2   
0                                    0                 0%   
1                                    1                 0%   
2                                    2                 0%   
3                                    3                 0%   
4                                    4                 0%   

GENDER_IND                                                        \
PRUDENCE_RELATED Raucher- übersterblichkeit Nichtraucher- faktor   
SMOKER_RELATED           Unnamed: 0_level_2   Unnamed: 0_level_2   
0                                      100%                  1.0   
1                                      100%                  1.0   
2                                      100%                  1.0   
3                                      100%                  1.0   
4                                      100%                  1.0   

GENDER_IND                                                         \
PRUDENCE_RELATED Sterblichkeit 2. Ordnung                           
SMOKER_RELATED                   Aggregat  Nichtraucher   Raucher   
0                                0.004562      0.004562  0.004562   
1                                0.000316      0.000316  0.000316   
2                                0.000256      0.000256  0.000256   
3                                0.000205      0.000205  0.000205   
4                                0.000164      0.000164  0.000164   

GENDER_IND                                                             \
PRUDENCE_RELATED Sterblichkeit 1. Ordnung                               
SMOKER_RELATED    Aggregat (Zuschlag 34%) Nichtraucher (Zuschlag 45%)   
0                                0.006113                    0.006113   
1                                0.000423                    0.000423   
2                                0.000343                    0.000343   
3                                0.000275                    0.000275   
4                                0.000220                    0.000220   

GENDER_IND                               DAV 2008T R/NR Frauen  \
PRUDENCE_RELATED                                         Alter   
SMOKER_RELATED   Raucher (Zuschlag 45%) Raucher (Zuschlag 45%)   
0                              0.006615                      0   
1                              0.000458                      1   
2                              0.000371                      2   
3                              0.000297                      3   
4                              0.000238                      4   

GENDER_IND                                                          \
PRUDENCE_RELATED          Raucheranteil Raucher- übersterblichkeit   
SMOKER_RELATED   Raucher (Zuschlag 45%)     Raucher (Zuschlag 45%)   
0                                    0%                       100%   
1                                    0%                       100%   
2                                    0%                       100%   
3                                    0%                       100%   
4                                    0%                       100%   

GENDER_IND                                                        \
PRUDENCE_RELATED   Nichtraucher- faktor Sterblichkeit 2. Ordnung   
SMOKER_RELATED   Raucher (Zuschlag 45%)                 Aggregat   
0                                   1.0                 0.003797   
1                                   1.0                 0.000289   
2                                   1.0                 0.000237   
3                                   1.0                 0.000190   
4                                   1.0                 0.000151   

GENDER_IND                                                         \
PRUDENCE_RELATED                         Sterblichkeit 1. Ordnung   
SMOKER_RELATED    Nichtraucher   Raucher  Aggregat (Zus

In [7]:
#headers_males = new_headers[4:10]
#headers_females = new_headers[14:]
#tab_DAV2008T_males = tab_DAV2008T[headers_males]
#tab_DAV2008T_females = tab_DAV2008T[headers_females]

#tab_DAV2008T_females.head()

In [8]:
tab_DAV2008T_transf = tab_DAV2008T[new_headers[list(range(4, 10)) + list(range(14, len(new_headers)))]]

#    .unstack().reset_index().drop("level_3", axis=1)
tab_DAV2008T_transf

GENDER_IND          DAV 2008T R/NR Männer                          \
PRUDENCE_RELATED Sterblichkeit 2. Ordnung                           
SMOKER_RELATED                   Aggregat  Nichtraucher   Raucher   
0                                0.004562      0.004562  0.004562   
1                                0.000316      0.000316  0.000316   
2                                0.000256      0.000256  0.000256   
3                                0.000205      0.000205  0.000205   
4                                0.000164      0.000164  0.000164   
..                                    ...           ...       ...   
117                              0.711028      0.711028  0.711028   
118                              0.732920      0.732920  0.732920   
119                              0.754701      0.754701  0.754701   
120                              0.776292      0.776292  0.776292   
121                              1.000000      1.000000  1.000000   

GENDER_IND                                                             \
PRUDENCE_RELATED Sterblichkeit 1. Ordnung                               
SMOKER_RELATED    Aggregat (Zuschlag 34%) Nichtraucher (Zuschlag 45%)   
0                                0.006113                    0.006113   
1                                0.000423                    0.000423   
2                                0.000343                    0.000343   
3                                0.000275                    0.000275   
4                                0.000220                    0.000220   
..                                    ...                         ...   
117                              0.952778                    0.952778   
118                              0.982113                    0.982113   
119                              1.000000                    1.000000   
120                              1.000000                    1.000000   
121                              1.000000                    1.000000   

GENDER_IND                                 DAV 2008T R/NR Frauen  \
PRUDENCE_RELATED                        Sterblichkeit 2. Ordnung   
SMOKER_RELATED   Raucher (Zuschlag 45%)                 Aggregat   
0                              0.006615                 0.003797   
1                              0.000458                 0.000289   
2                              0.000371                 0.000237   
3                              0.000297                 0.000190   
4                              0.000238                 0.000151   
..                                  ...                      ...   
117                            1.000000                 0.696026   
118                            1.000000                 0.716604   
119                            1.000000                 0.736988   
120                            1.000000                 0.757123   
121                            1.000000                 1.000000   

GENDER_IND                                                         \
PRUDENCE_RELATED                         Sterblichkeit 1. Ordnung   
SMOKER_RELATED    Nichtraucher   Raucher  Aggregat (Zuschlag 34%)   
0                     0.003797  0.003797                 0.005088   
1                     0.000289  0.000289                 0.000387   
2                     0.000237  0.000237                 0.000318   
3                     0.000190  0.000190                 0.000255   
4                     0.000151  0.000151                 0.000202   
..                         ...       ...                      ...   
117                   0.696026  0.696026                 0.932675   
118                   0.716604  0.716604                 0.960249   
119                   0.736988  0.736988                 0.987564   
120                   0.757123  0.757123                 1.000000   
121                   1.000000  1.000000                 1.000000   

GENDER_IND                                                           
PRUDENCE_RELATED    

In [9]:
from pyprotolinc.models.risk_factors import Gender, SmokerStatus, Age
from pyprotolinc.assumptions.providers import AssumptionType

remapped_headers = []

gender_map = {
    'DAV 2008T R/NR Männer': Gender.M,
    'DAV 2008T R/NR Frauen': Gender.F
}

assumption_type_map = {
    'Sterblichkeit 2. Ordnung': AssumptionType.BE,
    'Sterblichkeit 1. Ordnung': AssumptionType.RES,
}

smoker_map = {
   'Aggregat': SmokerStatus.A,
    ' Nichtraucher': SmokerStatus.N,
    'Raucher': SmokerStatus.S,
    'Aggregat (Zuschlag 34%)': SmokerStatus.A,
    'Nichtraucher (Zuschlag 45%)':SmokerStatus.N,
    'Raucher (Zuschlag 45%)': SmokerStatus.S
}

for col in tab_DAV2008T_transf.columns:
    remapped_headers.append((gender_map[col[0]], assumption_type_map[col[1]], smoker_map[col[2]]
    ))

tab_DAV2008T_transf.columns = remapped_headers


tab_DAV2008T_transf

(Gender.M, AssumptionType.BE, SmokerStatus.A)  \
0                                         0.004562   
1                                         0.000316   
2                                         0.000256   
3                                         0.000205   
4                                         0.000164   
..                                             ...   
117                                       0.711028   
118                                       0.732920   
119                                       0.754701   
120                                       0.776292   
121                                       1.000000   

     (Gender.M, AssumptionType.BE, SmokerStatus.N)  \
0                                         0.004562   
1                                         0.000316   
2                                         0.000256   
3                                         0.000205   
4                                         0.000164   
..                                             ...   
117                                       0.711028   
118                                       0.732920   
119                                       0.754701   
120                                       0.776292   
121                                       1.000000   

     (Gender.M, AssumptionType.BE, SmokerStatus.S)  \
0                                         0.004562   
1                                         0.000316   
2                                         0.000256   
3                                         0.000205   
4                                         0.000164   
..                                             ...   
117                                       0.711028   
118                                       0.732920   
119                                       0.754701   
120                                       0.776292   
121                                       1.000000   

     (Gender.M, AssumptionType.RES, SmokerStatus.A)  \
0                                          0.006113   
1                                          0.000423   
2                                          0.000343   
3                                          0.000275   
4                                          0.000220   
..                                              ...   
117                                        0.952778   
118                                        0.982113   
119                                        1.000000   
120                                        1.000000   
121                                        1.000000   

     (Gender.M, AssumptionType.RES, SmokerStatus.N)  \
0                                          0.006113   
1                                          0.000423   
2                                          0.000343   
3                                          0.000275   
4                                          0.000220   
..                                              ...   
117                                        0.952778   
118                                        0.982113   
119                                        1.000000   
120                                        1.000000   
121                                        1.000000   

     (Gender.M, AssumptionType.RES, SmokerStatus.S)  \
0                                          0.006615   
1                                          0.000458   
2                                          0.000371   
3                                          0.000297   
4                                          0.000238   
..                                              ...   
117                                        1.000000   
118                                        1.000000   
119                                        1.000000   
120                                        1.000000   
121                                        1.000000   

     (Gender.F, AssumptionType.BE, SmokerStatus.A)  \
0                    

In [10]:
# use a 3D array to store the rates with dimensions
# Age x Gender x Smoker

be_rates = np.zeros((len(tab_DAV2008T), 2, 3))
res_rates = np.zeros((len(tab_DAV2008T), 2, 3))

for g, at, ss in remapped_headers:
    if at == AssumptionType.BE:
        be_rates[:, g, ss] = tab_DAV2008T_transf[(g, at, ss)]
    elif at == AssumptionType.RES:
        res_rates[:, g, ss] = tab_DAV2008T_transf[(g, at, ss)]
    else:
        raise Exception("Unknown assumption type")
be_rates

array([[[4.56200e-03, 4.56200e-03, 4.56200e-03],
        [3.79700e-03, 3.79700e-03, 3.79700e-03]],

       [[3.16000e-04, 3.16000e-04, 3.16000e-04],
        [2.89000e-04, 2.89000e-04, 2.89000e-04]],

       [[2.56000e-04, 2.56000e-04, 2.56000e-04],
        [2.37000e-04, 2.37000e-04, 2.37000e-04]],

       [[2.05000e-04, 2.05000e-04, 2.05000e-04],
        [1.90000e-04, 1.90000e-04, 1.90000e-04]],

       [[1.64000e-04, 1.64000e-04, 1.64000e-04],
        [1.51000e-04, 1.51000e-04, 1.51000e-04]],

       [[1.36000e-04, 1.36000e-04, 1.36000e-04],
        [1.22000e-04, 1.22000e-04, 1.22000e-04]],

       [[1.16000e-04, 1.16000e-04, 1.16000e-04],
        [1.00000e-04, 1.00000e-04, 1.00000e-04]],

       [[1.04000e-04, 1.04000e-04, 1.04000e-04],
        [8.60000e-05, 8.60000e-05, 8.60000e-05]],

       [[9.80000e-05, 9.60000e-05, 9.60000e-05],
        [7.80000e-05, 7.80000e-05, 7.80000e-05]],

       [[9.60000e-05, 9.30000e-05, 9.30000e-05],
        [7.50000e-05, 7.40000e-05, 7.40000e-05]],



In [11]:

from pyprotolinc.assumptions.providers import StandardRatesProvider

In [12]:
provider_be = StandardRatesProvider(be_rates,
                                    (Age, Gender, SmokerStatus),
                                     offsets=(0, 0, 0))

provider_res = StandardRatesProvider(res_rates,
                                    (Age, Gender, SmokerStatus),
                                     offsets=(0, 0, 0))


In [13]:
ages = np.array([10, 20, 30], dtype=np.int32)
smokerstatus = np.array([SmokerStatus.S, SmokerStatus.N, SmokerStatus.A], dtype=np.int32)
genders = np.array([Gender.M, Gender.M, Gender.F], dtype=np.int32)


provider_be.get_rates(age=ages, smokerstatus=smokerstatus, gender=genders)

array([0.000101, 0.00073 , 0.000232])

In [14]:
provider_res.get_rates(age=ages, smokerstatus=smokerstatus, gender=genders)

array([0.000146, 0.001012, 0.000311])

In [15]:
# all three were manually checked against the input file and are ok

### Use Library functions

In [16]:
from pyprotolinc.assumptions.dav2008t import DAV2008T

In [20]:
lib_be_provider = DAV2008T().rates_provider(estimate_type="BE")
lib_res_provider = DAV2008T().rates_provider(estimate_type="LOADED")

In [21]:

lib_be_provider.get_rates(age=ages, smokerstatus=smokerstatus, gender=genders)

array([0.000101, 0.00073 , 0.000232])

In [22]:
lib_res_provider.get_rates(age=ages, smokerstatus=smokerstatus, gender=genders)

array([0.000146, 0.001012, 0.000311])

In [ ]:
# again ok