### Portfolio-Split

In [1]:
# load a portfolio
from pyprotolinc.models.model_disability_multistate import MultiStateDisabilityStates
from pyprotolinc.portfolio import Portfolio
portfolio_path = r"D:\programming\PyMultiState\pyprotolinc\data\portfolio\portfolio_med.xlsx"

# load the portfolio
portfolio = Portfolio(portfolio_path, MultiStateDisabilityStates)
portfolio

In [2]:
# the initial ages in (completed) months
portfolio.initial_ages

array([548, 633, 615, ..., 633, 615, 548], dtype=int64)

In [3]:
# IDEA: the assumptions are determined on a yearly basis so that they remain constant for 12 months
# for each insured but at which months they switch depends on the insured. More specifically, it depends on the age
# definition. Based on what we have so far that would depend on the age in months and months when assumptions 
# switch is the same for all records which differ in age my full years.

In [4]:
ages_groups = portfolio.initial_ages % 12
ages_groups

array([8, 9, 3, ..., 9, 3, 8], dtype=int64)

In [5]:
# illustration
import pandas as pd
df = pd.DataFrame({"ages": portfolio.initial_ages, "age_groups": ages_groups})
print(df["age_groups"].unique())
df.head()

[8 9 3]


ages  age_groups
0   548           8
1   633           9
2   615           3
3   548           8
4   633           9

In [6]:
import numpy as np
month_groups, group_inverses = np.unique(ages_groups, return_inverse=True)
month_groups, group_inverses

(array([3, 8, 9], dtype=int64), array([1, 2, 0, ..., 2, 0, 1], dtype=int64))

In [7]:
# an index for the parent
portfolio_index = np.arange(len(portfolio.initial_ages))
portfolio_index

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [8]:
sub_portfolio_indexes = [portfolio_index[ages_groups == k] for k in month_groups]

In [9]:
sub_portfolio_indexes

[array([   2,    5,    8, ..., 9992, 9995, 9998]),
 array([   0,    3,    6, ..., 9993, 9996, 9999]),
 array([   1,    4,    7, ..., 9991, 9994, 9997])]

In [10]:
# now use the functionality
subportfolios = portfolio.split_by_month_in_year()

In [11]:
subportfolios

In [12]:
[len(sp) for sp in subportfolios]

[3333, 3334, 3333]

In [16]:
[sp.common_month for sp in subportfolios], portfolio.common_month is None

([3, 8, 9], True)

True

In [18]:
for k, l in enumerate(('A', 'B')):
    print(k, l)

0 A
1 B
