### Products

In [1]:
import numpy as np
from sys import getsizeof

# start by getting some memory sizes

In [4]:
years = np.array([2022, 2022])
months = np.array([1, 2])
years, months, years.flags['C_CONTIGUOUS'], months.flags['C_CONTIGUOUS']

(array([2022, 2022]), array([1, 2]), True, True)

In [19]:
ta_abs = years * 12 + months - 1
ta_abs = ta_abs.reshape((1, ta_abs.shape[0]))
ta_abs, ta_abs.flags['C_CONTIGUOUS']

(array([[24264, 24265]]), True)

In [20]:
inception_yr = np.array([1990, 1991, 2005])
inception_months = np.array([2, 3, 4])
start_month_abs = (inception_yr * 12 + inception_months - 1).reshape((len(inception_yr), 1))
start_month_abs, start_month_abs.flags['C_CONTIGUOUS']

(array([[23881],
        [23894],
        [24063]]),
 True)

In [21]:
x = (ta_abs >= start_month_abs).astype(np.int16) #.transpose()
x, x.flags['C_CONTIGUOUS']

(array([[1, 1],
        [1, 1],
        [1, 1]], dtype=int16),
 True)

In [18]:
y = (start_month_abs <= ta_abs).astype(np.int16).transpose()
y, y.flags['C_CONTIGUOUS']

(array([[1, 1],
        [1, 1],
        [1, 1]], dtype=int16),
 False)

In [2]:
dim_state = 11
num_insureds = 256
timesteps = 120 * 12

a = np.ones((dim_state, num_insureds, timesteps), dtype=np.float64)
b = np.ones((dim_state, dim_state, num_insureds, timesteps), dtype=np.float64)

In [3]:
# size in MB
round(getsizeof(a) / 1024 / 1024, 2), round(getsizeof(b) / 1024 / 1024, 2)

(30.94, 340.31)

In [4]:
c = np.ones(1)
getsizeof(c)

120

In [5]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [6]:
x[:,None].shape

(3, 1)

### Test the annuity product

In [7]:
# get a portfolio
from pyprotolinc.models.model_annuity_runoff import AnnuityRunoffStates
from pyprotolinc.portfolio import Portfolio

portfolio_path = r"D:\programming\py\PyMultiState\pyprotolinc\data\portfolio\portfolio_annuity_small.xlsx"
portfolio = Portfolio(portfolio_path, AnnuityRunoffStates)

In [8]:
# this is just a simplification, in this example only the length counts
time_axis = np.arange(1, 11)

In [9]:
from pyprotolinc.runner import TimeAxis

In [10]:
ta = TimeAxis(portfolio.portfolio_date, 12)
len(ta)

13

In [15]:
# create a product
from pyprotolinc.product import Product_AnnuityInPayment, Product_TwoStateDisability

prod = Product_AnnuityInPayment(portfolio)
prod

In [12]:
prod.get_state_transition_payments(ta)

{}

In [13]:
prod.get_bom_payments(ta)

{<AnnuityRunoffStates.DIS1: 0>: [(<CfNames.ANNUITY_PAYMENT: 1>,
   array([[ -83.33333333,  -83.33333333,  -83.33333333,  -83.33333333,
            -83.33333333,  -83.33333333,  -83.33333333,  -83.33333333,
            -83.33333333,  -83.33333333,  -83.33333333,  -83.33333333,
            -83.33333333],
          [  -8.33333333,   -8.33333333,   -8.33333333,   -8.33333333,
             -8.33333333,   -8.33333333,   -8.33333333,   -8.33333333,
             -8.33333333,   -8.33333333,   -8.33333333,   -8.33333333,
             -8.33333333],
          [-416.66666667, -416.66666667, -416.66666667, -416.66666667,
           -416.66666667, -416.66666667, -416.66666667, -416.66666667,
           -416.66666667, -416.66666667, -416.66666667, -416.66666667,
           -416.66666667]]))]}

In [16]:
# the other Product
Product_TwoStateDisability(portfolio).get_bom_payments(ta)

{<MultiStateDisabilityStates.ACTIVE: 0>: [(<CfNames.PREMIUM: 0>,
   array([[ 8.33333333,  8.33333333,  8.33333333,  8.33333333,  8.33333333,
            8.33333333,  8.33333333,  8.33333333,  8.33333333,  8.33333333,
            8.33333333,  8.33333333,  8.33333333],
          [ 0.83333333,  0.83333333,  0.83333333,  0.83333333,  0.83333333,
            0.83333333,  0.83333333,  0.83333333,  0.83333333,  0.83333333,
            0.83333333,  0.83333333,  0.83333333],
          [41.66666667, 41.66666667, 41.66666667, 41.66666667, 41.66666667,
           41.66666667, 41.66666667, 41.66666667, 41.66666667, 41.66666667,
           41.66666667, 41.66666667, 41.66666667]]))],
 <MultiStateDisabilityStates.DIS1: 1>: [(<CfNames.ANNUITY_PAYMENT: 1>,
   array([[ -83.33333333,  -83.33333333,  -83.33333333,  -83.33333333,
            -83.33333333,  -83.33333333,  -83.33333333,  -83.33333333,
            -83.33333333,  -83.33333333,  -83.33333333,  -83.33333333,
            -83.33333333],
          [

In [18]:
Product_TwoStateDisability(portfolio).get_bom_payments((None,))

{<MultiStateDisabilityStates.ACTIVE: 0>: [(<CfNames.PREMIUM: 0>,
   array([[ 8.33333333],
          [ 0.83333333],
          [41.66666667]]))],
 <MultiStateDisabilityStates.DIS1: 1>: [(<CfNames.ANNUITY_PAYMENT: 1>,
   array([[ -83.33333333],
          [  -8.33333333],
          [-416.66666667]]))],
 <MultiStateDisabilityStates.DIS2: 2>: [(<CfNames.ANNUITY_PAYMENT: 1>,
   array([[-166.66666667],
          [ -16.66666667],
          [-833.33333333]]))]}