### Profiling

In [2]:
import pstats
from pstats import SortKey
import cProfile

from protolinc.main import project_cashflows_cli

In [4]:
%pwd
%cd d:\programming\PyMultiState

d:\programming\PyMultiState


In [10]:

cProfile.run('project_cashflows_cli()', 'profile.dat')

INFO - 2022-06-18 14:31:06,100 - protolinc.main - Mulistate run with config: {'model_name': 'MultiStateDisability', 'years_to_simulate': 120, 'portfolio_path': 'protolinc/data/portfolio/portfolio_med.xlsx', 'assumptions_path': 'run/di_assumptions.yaml', 'steps_per_month': 1, 'timestep_duration': 0.08333333333333333, 'outfile': 'run/_results/ncf_out_di.csv'}
INFO - 2022-06-18 14:31:07,059 - protolinc.portfolio - Reading portfolio data from file protolinc/data/portfolio/portfolio_med.xlsx.
INFO - 2022-06-18 14:31:14,908 - protolinc.portfolio - Portolio rows: 10000
DEBUG - 2022-06-18 14:31:14,912 - protolinc.runner - Calculating projection year 1.
DEBUG - 2022-06-18 14:31:15,033 - protolinc.runner - Calculating projection year 2.
DEBUG - 2022-06-18 14:31:15,139 - protolinc.runner - Calculating projection year 3.
DEBUG - 2022-06-18 14:31:15,257 - protolinc.runner - Calculating projection year 4.
DEBUG - 2022-06-18 14:31:15,401 - protolinc.runner - Calculating projection year 5.
DEBUG - 202

In [11]:

p = pstats.Stats('profile.dat')
p.strip_dirs().sort_stats(-1).print_stats()

Sat Jun 18 14:31:23 2022    profile.dat

         15108985 function calls (15099759 primitive calls) in 16.923 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 <__array_function__ internals>:2(all)
        7    0.000    0.000    0.000    0.000 <__array_function__ internals>:2(argsort)
       30    0.000    0.000    0.000    0.000 <__array_function__ internals>:2(array_equal)
        6    0.000    0.000    0.000    0.000 <__array_function__ internals>:2(copy)
     7021    0.012    0.000    0.144    0.000 <__array_function__ internals>:2(copyto)
      877    0.001    0.000    0.338    0.000 <__array_function__ internals>:2(isneginf)
      877    0.002    0.000    0.404    0.000 <__array_function__ internals>:2(isposinf)
      877    0.002    0.000    1.662    0.002 <__array_function__ internals>:2(nan_to_num)
426864/426826    0.114    0.000    0.413    0.000 <frozen importlib._boot

        1    0.000    0.000    0.000    0.000 __init__.py:71(search_function)
        1    0.000    0.000    0.000    0.000 __init__.py:72(check_states)
        1    0.000    0.000    0.000    0.000 __init__.py:727(__init__)
        2    0.000    0.000    0.017    0.009 __init__.py:74(load)
      158    0.000    0.000    0.000    0.000 __init__.py:747(filter)
        1    0.000    0.000    0.000    0.000 __init__.py:8(<module>)
        1    0.000    0.000    0.016    0.016 __init__.py:8(lxml_available)
      158    0.000    0.000    0.000    0.000 __init__.py:849(acquire)
      158    0.000    0.000    0.000    0.000 __init__.py:856(release)
       79    0.000    0.000    0.004    0.000 __init__.py:869(format)
       79    0.000    0.000    0.100    0.001 __init__.py:892(handle)
      432    0.002    0.000    0.009    0.000 __init__.py:9(__new__)
  376/371    0.000    0.000    0.001    0.000 _asarray.py:23(asarray)
       15    0.000    0.000    0.000    0.000 _asarray.py:293(require)


        2    0.000    0.000    0.002    0.001 base.py:3142(get_indexer)
       30    0.000    0.000    0.000    0.000 base.py:3304(_get_partial_string_timestamp_match_key)
        1    0.000    0.000    0.000    0.000 base.py:3314(_validate_positional_slice)
     2066    0.002    0.000    0.007    0.000 base.py:34(__init__)
     4561    0.003    0.000    0.005    0.000 base.py:38(__set__)
       28    0.000    0.000    0.000    0.000 base.py:381(<genexpr>)
       22    0.000    0.000    0.000    0.000 base.py:397(ndim)
       82    0.000    0.000    0.000    0.000 base.py:4070(_values)
       25    0.000    0.000    0.000    0.000 base.py:4096(_get_engine_target)
      632    0.001    0.000    0.001    0.000 base.py:411(find)
        6    0.000    0.000    0.000    0.000 base.py:4230(__contains__)
       42    0.000    0.000    0.000    0.000 base.py:425(_simple_new)
       75    0.000    0.000    0.000    0.000 base.py:4279(__getitem__)
       23    0.000    0.000    0.002    0.000 ba

      108    0.000    0.000    0.001    0.000 common.py:1187(needs_i8_conversion)
        1    0.000    0.000    0.000    0.000 common.py:1234(is_numeric_dtype)
       13    0.000    0.000    0.000    0.000 common.py:126(_expand_user)
       14    0.000    0.000    0.000    0.000 common.py:1276(is_string_like_dtype)
      130    0.000    0.000    0.000    0.000 common.py:129(cast_scalar_indexer)
       14    0.000    0.000    0.000    0.000 common.py:1304(<lambda>)
       63    0.000    0.000    0.000    0.000 common.py:1307(is_float_dtype)
       58    0.000    0.000    0.000    0.000 common.py:1341(is_bool_dtype)
       22    0.000    0.000    0.000    0.000 common.py:145(validate_header_arg)
      620    0.001    0.000    0.001    0.000 common.py:1470(is_extension_array_dtype)
       22    0.000    0.000    0.000    0.000 common.py:1519(is_complex_dtype)
        8    0.000    0.000    0.000    0.000 common.py:154(stringify_path)
      182    0.000    0.000    0.000    0.000 common.p

        3    0.000    0.000    0.000    0.000 datetimes.py:735(_local_timestamps)
        3    0.000    0.000    0.002    0.001 datetimes.py:80(f)
        1    0.000    0.000    0.000    0.000 defined_name.py:167(DefinedNameList)
        2    0.000    0.000    0.000    0.000 defined_name.py:174(__init__)
        1    0.000    0.000    0.005    0.005 defined_name.py:3(<module>)
        1    0.000    0.000    0.000    0.000 defined_name.py:65(DefinedName)
        1    0.000    0.000    0.000    0.000 descriptors.py:18(NestedGapAmount)
        1    0.000    0.000    0.000    0.000 descriptors.py:25(NestedOverlap)
        1    0.000    0.000    0.000    0.000 descriptors.py:32(NumberFormatDescriptor)
        1    0.000    0.000    0.000    0.000 descriptors.py:5(<module>)
        1    0.000    0.000    0.000    0.000 differential.py:19(DifferentialStyle)
        1    0.000    0.000    0.000    0.000 differential.py:3(<module>)
        1    0.000    0.000    0.000    0.000 differential.py:5

        1    0.000    0.000    0.000    0.000 format.py:929(__init__)
        1    0.000    0.000    0.000    0.000 formatting.py:1103(XFBorder)
        1    0.000    0.000    0.000    0.000 formatting.py:1170(XFBackground)
        1    0.000    0.000    0.000    0.000 formatting.py:1190(XFAlignment)
        1    0.000    0.000    0.000    0.000 formatting.py:1224(XFProtection)
        1    0.000    0.000    0.000    0.000 formatting.py:1243(XF)
        1    0.000    0.000    0.000    0.000 formatting.py:154(EqNeAttrs)
        1    0.000    0.000    0.000    0.000 formatting.py:166(Font)
        1    0.000    0.000    0.000    0.000 formatting.py:19(ConditionalFormatting)
        1    0.000    0.000    0.001    0.001 formatting.py:3(<module>)
        1    0.000    0.000    0.000    0.000 formatting.py:332(Format)
        1    0.000    0.000    0.000    0.000 formatting.py:57(ConditionalFormattingList)
        2    0.000    0.000    0.000    0.000 formatting.py:61(__init__)
        1   

       33    0.000    0.000    0.000    0.000 parsers.py:1097(_is_potential_multi_index)
       66    0.000    0.000    0.000    0.000 parsers.py:1121(<genexpr>)
       11    0.000    0.000    0.000    0.000 parsers.py:1169(_validate_skipfooter_arg)
       11    0.000    0.000    0.000    0.000 parsers.py:1199(_validate_usecols_arg)
       11    0.000    0.000    0.000    0.000 parsers.py:1249(_validate_parse_dates_arg)
       11    0.000    0.000    0.000    0.000 parsers.py:1272(__init__)
       11    0.000    0.000    0.000    0.000 parsers.py:1371(_validate_parse_dates_presence)
       11    0.000    0.000    0.000    0.000 parsers.py:1407(<setcomp>)
       11    0.000    0.000    0.000    0.000 parsers.py:1423(_has_complex_date_col)
       22    0.000    0.000    0.000    0.000 parsers.py:1509(_maybe_dedup_names)
       11    0.000    0.000    0.000    0.000 parsers.py:1539(_maybe_make_multi_index_columns)
       11    0.000    0.000    0.000    0.000 parsers.py:1545(_make_index)


        1    0.000    0.000    0.000    0.000 rule.py:135(Rule)
        1    0.000    0.000    0.000    0.000 rule.py:21(ValueDescriptor)
        1    0.000    0.000    0.002    0.002 rule.py:3(<module>)
        1    0.000    0.000    0.000    0.000 rule.py:39(FormatObject)
        1    0.000    0.000    0.000    0.000 rule.py:61(RuleType)
        1    0.000    0.000    0.000    0.000 rule.py:66(IconSet)
        1    0.000    0.000    0.000    0.000 rule.py:94(DataBar)
      877    0.011    0.000    0.441    0.001 runner.py:112(calc_payments_bom)
        1    0.000    0.000    0.000    0.000 runner.py:12(__init__)
      877    0.011    0.000    0.289    0.000 runner.py:128(calc_payments_eom)
        1    0.185    0.185    8.060    8.060 runner.py:143(run)
        1    0.000    0.000    0.001    0.001 runner.py:25(__init__)
      877    0.005    0.000    1.142    0.001 runner.py:88(update_state)
      877    0.612    0.001    1.067    0.001 runner.py:91(select_applicable_base_assumption

https://qxf2.com/blog/saving-cprofile-stats-to-a-csv-file/

In [5]:
import cProfile
import pstats, math
import io
import pandas as pd
 
pr = cProfile.Profile()
pr.enable()
project_cashflows_cli()
pr.disable()
 
result = io.StringIO()
pstats.Stats(pr,stream=result).print_stats()
result=result.getvalue()
# chop the string into a csv-like buffer
result='ncalls'+result.split('ncalls')[-1]
result='\n'.join([','.join(line.rstrip().split(None,5)) for line in result.split('\n')])
# save it to disk
 
with open('profile_test.csv', 'w+') as f:
    #f=open(result.rsplit('.')[0]+'.csv','w')
    f.write(result)
    f.close()


INFO - 2022-06-19 10:55:32,183 - protolinc.main - Mulistate run with config: {'model_name': 'MultiStateDisability', 'years_to_simulate': 10, 'portfolio_path': 'protolinc/data/portfolio/portfolio_small.xlsx', 'assumptions_path': 'run/di_assumptions.yaml', 'steps_per_month': 1, 'timestep_duration': 0.08333333333333333, 'outfile': 'run/_results/ncf_out_di.csv', 'portfolio_cache': 'run/portfolio_cache'}
DEBUG - 2022-06-19 10:55:32,603 - protolinc.portfolio - Porfolio file not found in cache.
INFO - 2022-06-19 10:55:32,605 - protolinc.portfolio - Reading portfolio data from file d:\programming\PyMultiState\protolinc\data\portfolio\portfolio_small.xlsx.
INFO - 2022-06-19 10:55:32,633 - protolinc.portfolio - Portolio rows: 3
INFO - 2022-06-19 10:55:32,634 - protolinc.portfolio - Porfolio saved in cache
DEBUG - 2022-06-19 10:55:32,637 - protolinc.runner - Calculating projection year 1.
DEBUG - 2022-06-19 10:55:32,642 - protolinc.runner - Calculating projection year 2.
DEBUG - 2022-06-19 10:55:

In [11]:
df = pd.read_csv(io.StringIO(result))

In [14]:
df_filtered = df[(df["filename:lineno(function)"].str.contains("protolinc")) &
                 (df.cumtime > 0)].copy()
df_filtered.head()

ncalls  tottime  percall  cumtime  percall.1  \
921       1    0.000      0.0    0.009      0.009   
1064      1    0.000      0.0    0.419      0.419   
1065      1    0.000      0.0    0.523      0.523   
1066      1    0.000      0.0    0.532      0.532   
1095    120    0.002      0.0    0.002      0.000   

                              filename:lineno(function)  
921   d:\programming\pymultistate\protolinc\__i...  
1064  d:\programming\pymultistate\protolinc\mai...  
1065  d:\programming\pymultistate\protolinc\mai...  
1066  d:\programming\pymultistate\protolinc\mai...  
1095  d:\programming\pymultistate\protolinc\pro...

In [15]:
# common prefix
start_pos = df_filtered["filename:lineno(function)"].str.find("protolinc").unique()[0]
df_filtered["filename:lineno(function)"] = df_filtered["filename:lineno(function)"].str.slice(start_pos)

In [23]:
import numpy as np
df_filtered.index = np.arange(1, 1 + len(df_filtered))

In [24]:
df_filtered

ncalls  tottime  percall  cumtime  percall.1  \
1       1    0.000    0.000    0.009      0.009   
2       1    0.000    0.000    0.419      0.419   
3       1    0.000    0.000    0.523      0.523   
4       1    0.000    0.000    0.532      0.532   
5     120    0.002    0.000    0.002      0.000   
6       1    0.000    0.000    0.028      0.028   
7       1    0.000    0.000    0.005      0.005   
8       1    0.000    0.000    0.033      0.033   
9       1    0.000    0.000    0.001      0.001   
10      1    0.000    0.000    0.002      0.002   
11      1    0.000    0.000    0.010      0.010   
12    120    0.000    0.000    0.007      0.000   
13    120    0.005    0.000    0.018      0.000   
14    120    0.000    0.000    0.003      0.000   
15    120    0.001    0.000    0.007      0.000   
16      1    0.001    0.001    0.058      0.058   
17    480    0.001    0.000    0.003      0.000   
18    720    0.001    0.000    0.001      0.000   
19    720    0.005    0.000    0.009      0.000   
20    120    0.001    0.000    0.008      0.000   
21    120    0.006    0.000    0.007      0.000   
22    121    0.001    0.000    0.006      0.000   
23    120    0.002    0.000    0.004      0.000   
24     10    0.000    0.000    0.072      0.007   
25      1    0.000    0.000    0.333      0.333   
26     10    0.000    0.000    0.072      0.007   
27      1    0.000    0.000    0.014      0.014   
28      1    0.000    0.000    0.405      0.405   

                            filename:lineno(function)  
1   protolinc\__init__.py:42(get_config_from_...  
2             protolinc\main.py:26(create_model)  
3        protolinc\main.py:68(project_cashflows)  
4   protolinc\main.py:103(project_cashflows_cli)  
5      protolinc\product.py:15(get_bom_payments)  
6            protolinc\portfolio.py:22(__init__)  
7   protolinc\portfolio.py:51(completed_month...  
8                protolinc\portfolio.py:85(load)  
9   protolinc\portfolio.py:116(_load_from_cache)  
10    protolinc\portfolio.py:128(_save_in_cache)  
11       protolinc\results.py:34(export_results)  
12          protolinc\runner.py:88(update_state)  
13  protolinc\runner.py:91(select_applicable_...  
14    protolinc\runner.py:112(calc_payments_bom)  
15    protolinc\runner.py:128(calc_payments_eom)  
16                  protolinc\runner.py:143(run)  
17  protolinc\assumptions\providers.py:33(get...  
18  protolinc\assumptions\providers.py:61(<di...  
19  protolinc\assumptions\providers.py:57(get...  
20  protolinc\assumptions\providers.py:129(ad...  
21  protolinc\models\model_disability_multist...  
22  protolinc\models\model_disability_multist...  
23  protolinc\models\model_disability_multist...  
24  protolinc\assumptions\iohelpers.py:25(rea...  
25  protolinc\assumptions\iohelpers.py:81(__e...  
26  protolinc\assumptions\iohelpers.py:91(_re...  
27  protolinc\assumptions\iohelpers.py:127(__...  
28  protolinc\assumptions\iohelpers.py:135(load)

In [28]:
# some sorting?

In [29]:
df_filtered.to_excel("profile.xlsx")

In [27]:
import numpy as np

a = np.arange(24).reshape((3, 2, 4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
a.sum(axis=1)

array([[ 4,  6,  8, 10],
       [20, 22, 24, 26],
       [36, 38, 40, 42]])

In [29]:
a[:, ]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [30]:
b = np.arange(16).reshape((2, 2, 4))
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [31]:
b[:, 0, :]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [33]:
b[:, 0, :].sum(axis=0)

array([ 8, 10, 12, 14])

In [38]:
from enum import IntEnum, unique
from protolinc.models.model_disability_multistate import MultiStateDisabilityStates

x = MultiStateDisabilityStates.ACTIVE
x

<MultiStateDisabilityStates.ACTIVE: 0>

In [39]:
isinstance(x, IntEnum)

True