### Trivial Rate Providers

In [1]:
import numpy as np
from pyprotolinc.assumptions.providers import ConstantRateProvider
import pyprotolinc._actuarial as actuarial

In [2]:
zero_provider = ConstantRateProvider(0.0)
flat_provider = ConstantRateProvider(0.05)

In [3]:
zero_provider.get_rates(length=14)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
flat_provider.get_rates(length=4)

array([0.05, 0.05, 0.05, 0.05])

### Simple Standard RatesProvider

In [5]:
vals2D = np.array([
        [1, 2, 3],
        [4, 5, 6]], dtype=np.float64)

offsets = np.zeros(2, dtype=np.int32)
offsets[0] = 2
    # dimension mismatch should produce an exception

providerS = actuarial.StandardRateProvider([actuarial.CRiskFactors.Gender, actuarial.CRiskFactors.Age], vals2D, offsets)

In [6]:
# test new methods
providerS.get_shape() == (2, 3)

True

In [8]:
np.array_equal(providerS.get_offsets(), offsets)

True

In [9]:
providerS.get_values().reshape(vals2D.shape)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
import pickle

In [11]:
serialized = pickle.dumps(providerS)
serialized

b'\x80\x04\x95e\x01\x00\x00\x00\x00\x00\x00\x8c\x16pyprotolinc._actuarial\x94\x8c\x1crebuild_StandardRateProvider\x94\x93\x94]\x94(h\x00\x8c\x0cCRiskFactors\x94\x93\x94K\x01\x85\x94R\x94h\x05K\x00\x85\x94R\x94e\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x02K\x03\x86\x94h\r\x8c\x05dtype\x94\x93\x94\x8c\x02f8\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C0\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x94t\x94bh\x0ch\x0fK\x00\x85\x94h\x11\x87\x94R\x94(K\x01K\x02\x85\x94h\x16\x8c\x02i4\x94\x89\x88\x87\x94R\x94(K\x03h\x1aNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C\x08\x02\x00\x00\x00\x00\x00\x00\x00\x94t\x94b\x87\x94R\x94.'

In [12]:
providerS2 = pickle.loads(serialized)
providerS2

<CStandardRateProvider with RF (Gender, Age)>

In [15]:
providerS2.get_shape() == providerS.get_shape()

True

In [17]:
# cmp values
np.array_equal(providerS2.get_values().reshape(providerS2.get_shape()), providerS.get_values().reshape(providerS.get_shape()))

True

In [20]:
serialized2 = pickle.dumps(providerS2)
serialized2

b'\x80\x04\x95e\x01\x00\x00\x00\x00\x00\x00\x8c\x16pyprotolinc._actuarial\x94\x8c\x1crebuild_StandardRateProvider\x94\x93\x94]\x94(h\x00\x8c\x0cCRiskFactors\x94\x93\x94K\x01\x85\x94R\x94h\x05K\x00\x85\x94R\x94e\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x02K\x03\x86\x94h\r\x8c\x05dtype\x94\x93\x94\x8c\x02f8\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C0\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x94t\x94bh\x0ch\x0fK\x00\x85\x94h\x11\x87\x94R\x94(K\x01K\x02\x85\x94h\x16\x8c\x02i4\x94\x89\x88\x87\x94R\x94(K\x03h\x1aNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C\x08\x02\x00\x00\x00\x00\x00\x00\x00\x94t\x94b\x87\x94R\x94.'

In [21]:
serialized2 == serialized

True

In [22]:
providerC = actuarial.ConstantRateProvider(0.6)

### Rates providers from Tables

In [ ]:
from pyprotolinc.assumptions.tables import AssumptionsTable1D
import pyprotolinc.risk_factors as risk_factors


In [ ]:
simple_mort_table = AssumptionsTable1D(np.arange(120) / 120, risk_factors.Age)

In [ ]:
# inspect the values
simple_mort_table.values

In [ ]:
# try out some other shapes
test_arr = np.arange(120) / 120
AssumptionsTable1D(test_arr.reshape((120, 1)), risk_factors.Age).values

In [ ]:
AssumptionsTable1D(test_arr.reshape((1, 120)), risk_factors.Age).values

In [ ]:
AssumptionsTable1D(test_arr.reshape((120, 1)), risk_factors.Gender).values

In [ ]:
rp = simple_mort_table.rates_provider()
rp

In [ ]:
rp.get_rates(age=np.array([1, 2, 1, 0]))

### 2D Assumptions

In [ ]:
from pyprotolinc.assumptions.tables import AssumptionsTable2D

In [ ]:
asssumptions = np.dot(np.arange(120).reshape((120, 1)) / 120, np.array([[1, 0.8]]))
asssumptions

In [ ]:
simple_2d_table = AssumptionsTable2D(asssumptions, risk_factors.Age, risk_factors.Gender)
provider2 = simple_2d_table.rates_provider()

In [ ]:
ages = np.array([1, 2, 1])
genders = np.array([risk_factors.Gender.M, risk_factors.Gender.F, risk_factors.Gender.F])
provider2.get_rates(age=ages, gender=genders)