### Trivial Rate Providers

In [28]:
from pyprotolinc.assumptions.providers import ConstantRateProvider

In [29]:
zero_provider = ConstantRateProvider(0.0)
flat_provider = ConstantRateProvider(0.05)

In [30]:
zero_provider.get_rates(length=14)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
flat_provider.get_rates(length=4)

array([0.05, 0.05, 0.05, 0.05])

### Rates providers from Tables

In [33]:
from pyprotolinc.assumptions.tables import AssumptionsTable1D
import pyprotolinc.risk_factors as risk_factors
import numpy as np

In [34]:
simple_mort_table = AssumptionsTable1D(np.arange(120) / 120, risk_factors.Age)

In [35]:
# inspect the values
simple_mort_table.values

array([0.        , 0.00833333, 0.01666667, 0.025     , 0.03333333,
       0.04166667, 0.05      , 0.05833333, 0.06666667, 0.075     ,
       0.08333333, 0.09166667, 0.1       , 0.10833333, 0.11666667,
       0.125     , 0.13333333, 0.14166667, 0.15      , 0.15833333,
       0.16666667, 0.175     , 0.18333333, 0.19166667, 0.2       ,
       0.20833333, 0.21666667, 0.225     , 0.23333333, 0.24166667,
       0.25      , 0.25833333, 0.26666667, 0.275     , 0.28333333,
       0.29166667, 0.3       , 0.30833333, 0.31666667, 0.325     ,
       0.33333333, 0.34166667, 0.35      , 0.35833333, 0.36666667,
       0.375     , 0.38333333, 0.39166667, 0.4       , 0.40833333,
       0.41666667, 0.425     , 0.43333333, 0.44166667, 0.45      ,
       0.45833333, 0.46666667, 0.475     , 0.48333333, 0.49166667,
       0.5       , 0.50833333, 0.51666667, 0.525     , 0.53333333,
       0.54166667, 0.55      , 0.55833333, 0.56666667, 0.575     ,
       0.58333333, 0.59166667, 0.6       , 0.60833333, 0.61666

In [36]:
# try out some other shapes
test_arr = np.arange(120) / 120
AssumptionsTable1D(test_arr.reshape((120, 1)), risk_factors.Age).values

array([0.        , 0.00833333, 0.01666667, 0.025     , 0.03333333,
       0.04166667, 0.05      , 0.05833333, 0.06666667, 0.075     ,
       0.08333333, 0.09166667, 0.1       , 0.10833333, 0.11666667,
       0.125     , 0.13333333, 0.14166667, 0.15      , 0.15833333,
       0.16666667, 0.175     , 0.18333333, 0.19166667, 0.2       ,
       0.20833333, 0.21666667, 0.225     , 0.23333333, 0.24166667,
       0.25      , 0.25833333, 0.26666667, 0.275     , 0.28333333,
       0.29166667, 0.3       , 0.30833333, 0.31666667, 0.325     ,
       0.33333333, 0.34166667, 0.35      , 0.35833333, 0.36666667,
       0.375     , 0.38333333, 0.39166667, 0.4       , 0.40833333,
       0.41666667, 0.425     , 0.43333333, 0.44166667, 0.45      ,
       0.45833333, 0.46666667, 0.475     , 0.48333333, 0.49166667,
       0.5       , 0.50833333, 0.51666667, 0.525     , 0.53333333,
       0.54166667, 0.55      , 0.55833333, 0.56666667, 0.575     ,
       0.58333333, 0.59166667, 0.6       , 0.60833333, 0.61666

In [37]:
AssumptionsTable1D(test_arr.reshape((1, 120)), risk_factors.Age).values

array([0.        , 0.00833333, 0.01666667, 0.025     , 0.03333333,
       0.04166667, 0.05      , 0.05833333, 0.06666667, 0.075     ,
       0.08333333, 0.09166667, 0.1       , 0.10833333, 0.11666667,
       0.125     , 0.13333333, 0.14166667, 0.15      , 0.15833333,
       0.16666667, 0.175     , 0.18333333, 0.19166667, 0.2       ,
       0.20833333, 0.21666667, 0.225     , 0.23333333, 0.24166667,
       0.25      , 0.25833333, 0.26666667, 0.275     , 0.28333333,
       0.29166667, 0.3       , 0.30833333, 0.31666667, 0.325     ,
       0.33333333, 0.34166667, 0.35      , 0.35833333, 0.36666667,
       0.375     , 0.38333333, 0.39166667, 0.4       , 0.40833333,
       0.41666667, 0.425     , 0.43333333, 0.44166667, 0.45      ,
       0.45833333, 0.46666667, 0.475     , 0.48333333, 0.49166667,
       0.5       , 0.50833333, 0.51666667, 0.525     , 0.53333333,
       0.54166667, 0.55      , 0.55833333, 0.56666667, 0.575     ,
       0.58333333, 0.59166667, 0.6       , 0.60833333, 0.61666

In [38]:
AssumptionsTable1D(test_arr.reshape((120, 1)), risk_factors.Gender).values

AssertionError: Required length of assumptions does not fit for Gender

In [39]:
rp = simple_mort_table.rates_provider()
rp

<StandardRatesProvider with factors (['age'])>

In [40]:
rp.get_rates(age=np.array([1, 2, 1, 0]))

array([0.00833333, 0.01666667, 0.00833333, 0.        ])

### 2D Assumptions

In [41]:
from pyprotolinc.assumptions.tables import AssumptionsTable2D

In [42]:
asssumptions = np.dot(np.arange(120).reshape((120, 1)) / 120, np.array([[1, 0.8]]))
asssumptions

array([[0.        , 0.        ],
       [0.00833333, 0.00666667],
       [0.01666667, 0.01333333],
       [0.025     , 0.02      ],
       [0.03333333, 0.02666667],
       [0.04166667, 0.03333333],
       [0.05      , 0.04      ],
       [0.05833333, 0.04666667],
       [0.06666667, 0.05333333],
       [0.075     , 0.06      ],
       [0.08333333, 0.06666667],
       [0.09166667, 0.07333333],
       [0.1       , 0.08      ],
       [0.10833333, 0.08666667],
       [0.11666667, 0.09333333],
       [0.125     , 0.1       ],
       [0.13333333, 0.10666667],
       [0.14166667, 0.11333333],
       [0.15      , 0.12      ],
       [0.15833333, 0.12666667],
       [0.16666667, 0.13333333],
       [0.175     , 0.14      ],
       [0.18333333, 0.14666667],
       [0.19166667, 0.15333333],
       [0.2       , 0.16      ],
       [0.20833333, 0.16666667],
       [0.21666667, 0.17333333],
       [0.225     , 0.18      ],
       [0.23333333, 0.18666667],
       [0.24166667, 0.19333333],
       [0.

In [43]:
simple_2d_table = AssumptionsTable2D(asssumptions, risk_factors.Age, risk_factors.Gender)
provider2 = simple_2d_table.rates_provider()

In [44]:
ages = np.array([1, 2, 1])
genders = np.array([risk_factors.Gender.M, risk_factors.Gender.F, risk_factors.Gender.F])
provider2.get_rates(age=ages, gender=genders)

array([0.00833333, 0.01333333, 0.00666667])